apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "9"
    argocd.argoproj.io/hook: PostSync
  name: {{ .Values.job.name }}
  namespace: {{ .Values.job.namespace }}
spec:
  template:
    spec:
      containers: 
      - image: {{ .Values.job.image }}
        command:
        - /bin/bash
        - -c
        - |
{{- include "odf.jobs" . | nindent 10 }}
        name: {{ .Values.job.name }}
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      serviceAccount: {{ .Values.job.serviceAccount }}
      serviceAccountName: {{ .Values.job.serviceAccountName }}
      terminationGracePeriodSeconds: 30

