apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: {{ .Values.kafka.cluster.name }}
  namespace: "{{ .Values.global.xraylab.namespace }}"
spec:
  entityOperator:
    topicOperator:
      reconciliationIntervalSeconds: 90
    userOperator:
      reconciliationIntervalSeconds: 120
  kafka:
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.min.isr: 1
      transaction.state.log.replication.factor: 1
    listeners:
{{- range .Values.kafka.config.listeners }}
      - name: {{ .name }}
        port: {{ .port }}
        type: {{ .type }}
        tls: {{ .tls }}
{{- end }}
    replicas: {{ .Values.kafka.replicas }}
    storage:
      type: {{ .Values.kafka.storage.type }}
  zookeeper:
    replicas: {{ .Values.zookeeper.replicas }}
    storage:
      type: {{ .Values.zookeeper.storage.type }}
